### ISSUE TITLE
Transition from matcher

### ISSUE THREAD

**Issue by vtm9** [state-machines/state_machines-rspec#5]
I think transition from matcher more flexible and useful. And make a pull request [https://github.com/state-machines/state_machines-rspec/pulls](url)  Can anybody merge it and tag new version of gem. Thanks all!

**Comment by rafaelfranca** [comment]
Thank you but there is no need to open a new issue if there is a pull request open. I'm not an user of RSpec so I don't have context to review, merge and release that pull request. I'll leave to someone that does.
