### ISSUE TITLE
Support for transition from 'any'

### ISSUE THREAD

**Issue by SirRawlins** [state-machines/state_machines-rspec#6]
I have several state machines which allow transitioning from `any` state on a given event.

```ruby
# Example state machine with a transition from 'any'.
state_machine :state do
    # Transition back to an open state.
    transition any => :open, :on => :open

    #...
end
```
However, these are currently verbose to test using the `transitions_from` matcher, as I have to explicitly pass in every single state - for which there may be many.

```ruby
# Example spec with explicite from definitions.
it { is_expected.to transitions_from :foo, :bar, :foobar, :etc, to_state: :open, on_event: :open}
```

I'd like to propose an `:any` option on the matcher, which may make this easier?

```ruby
# Example spec with proposed :any from definition.
it { is_expected.to transitions_from :any, to_state: :open, on_event: :open}
```

What are your thoughts on this? Anyone else find this useful?

**Comment by vtm9** [comment]
@SirRawlins, I think it is a good idea. But I named it `:_any_`. Maybe somebody have state `any` in state machine.
@seuros  what do you think about it?

**Comment by tom-lord** [comment]
:+1: Something I'd like to add to my tests is determining "**final** states". So for example, suppose we have a simple state of `finished` - then I'd like to write a test such as:

    it { is_expected.to reject_events :_any_, when: :finished }

I can of course define this test "manually", but from what I can tell there's currently no nice syntactic sugar for it (like above) provided by this library.

**Comment by vtm9** [comment]
@tom-lord, It's good idea. But nobody merge my PR. So I don't think that it will be in gem.

**Comment by seuros** [comment]
@vtm9 it will. :)
