### ISSUE TITLE
uninitialized constant StateMachinesRspec

### ISSUE THREAD

**Issue by vernistage** [state-machines/state_machines-rspec#7]
I tried adding the gem to :test, then to :development, :test and bundle installing each time and running my test suite, but I keep getting "uninitialized constant StateMachinesRspec". Is Rails having trouble locating the StateMachinesRspec file because you renamed the module's main file to use a '-' instead of an '_'? I can't figure it out otherwise.

**Comment by seuros** [comment]
I'm going to look into it now.

**Comment by seuros** [comment]
@vernistage can you try 0.5.0. It should work out of the box.
